#!/bin/sh
#set -x

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --cached $against -- | cut -c100-` ; do
    #test if it's a sqlite database.  Prevent committing those.
    file $FILE | grep 'SQLite'
    status=$?
    if [ $status -eq 0 ] ; then
        echo $FILE ' is a SQLite file. They may contain passwords. Do not commit this file.'
        exit 1
    fi

    #test if a file contains a secret key. Prevent committing those.
    if [ "grep 'SECRET_KEY' $FILE" ] ; then
        echo $FILE ' contains a Django SECRET_KEY. This can not be committed.'
        exit 1
    fi
done
exit
